export const GET_LATEST_ESTIMATOR = 'settings/GET_LATEST_ESTIMATOR';

export const USER_PROFILE_QUERY_KEY = 'me';

export const DASHBOARD_QUERY_KEY_PREFIX = 'dashboard';

export const SESSIONS_QUERY_KEY = 'GET_SESSIONS';

export const SAMPLES_QUERY_KEY = 'GET_SAMPLES';

export const USER_STATISTICS_QUERY_KEY = 'GET_USER_STATISTICS';

export const SAMPLE_STATISTICS_QUERY_KEY = 'GET_SAMPLE_STATISTICS';

export const VERIFICATION_STATISTICS_QUERY_KEY = 'GET_VERIFICATION_STATISTICS';
